FROM grafana/grafana:latest
ADD ./provisioning /etc/grafana/provisioning
ADD ./dashboards/Spring_Boot.json /etc/grafana/provisioning/dashboards/Spring_Boot.json
ADD ./dashboards/rabbitmq.json /etc/grafana/provisioning/dashboards/rabbitmq.json