name: Build/test/Publish

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: micro-services
        path: |
          ./micro-collector/target/micro-collector-1.0-SNAPSHOT.jar
          ./micro-sender/target/micro-sender-1.0-SNAPSHOT.jar
          ./micro-recipient/target/micro-recipient-1.0-SNAPSHOT.jar
    
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Move folders
        run: ls
        shell: bash
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Buildx docker and push
        run: |
          cd micro-collector
          ls target
          docker buildx build \
            -t "ghcr.io/merczmisi/epam-l2-microservices/micro-collector:latest" \
            -f ./Dockerfile \
            --push .
            
            


