name: Build/test/Publish

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest
    outputs:
      jar_version: ${{ steps.bump.outputs.jar_version }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Bump jar version
      id: bump
      run: |
        echo "sha_sort=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT
        echo "jar_version=1.0.${{ github_run_number }}" >> $GITHUB_OUTPUT
        cat $GITHUB_OUTPUT
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Github Container Registry
      uses: docker/setup-buildx-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrects.GITHUB_TOKEN }}
        
    - name: Build and push the Docker image
      uses: docker/setup-buildx-action@v3
      with:
        push: true
        tags: |
          ghcr.io/merczmisi/epam-l2-microservices:latest
          ghcr.io/merczmisi/epam-l2-microservices:${{ steps.bump.outputs.jar_version }}
          ghcr.io/merczmisi/epam-l2-microservices:${{ steps.bump.outputs.scha_short }}
        cache-form: type=gha
        cache-to: type=gha,mode=max
        
  run:
    runs-on: ubuntu-22.04
    needs: [build]
    
    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Run container
      run: |
        echo "${{ needs-build.outputs.jar_version }}"
        echo "${{ needs-build.outputs.sha_short }}"
      
