name: Build/test/Publish

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Buildx docker and push
        run: |
          cd micro-collector
          docker buildx build \
            -t "ghcr.io/merczmisi/epam-l2-microservices/micro-collector:latest" \
            -f ./Dockerfile \
            --push .
            
          cd ..
          cd micro-sender
          docker buildx build \
            -t "ghcr.io/merczmisi/epam-l2-microservices/micro-sender:latest" \
            -f ./Dockerfile \
            --push .
          
          cd ..
          cd micro-recipient
          docker buildx build \
            -t "ghcr.io/merczmisi/epam-l2-microservices/micro-recipient:latest" \
            -f ./Dockerfile \
            --push .
            
            


