name: Build/test/Publish

on:
  [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: mvn clean package
    
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./micro-collector/Dockerfile
          push: true
          tags: |
            ghcr.io/merczmisi/epam-l2-microservices/micro-collector:latest
